In [8]:
import numpy as np
import pandas as pd
import seaborn as sb
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

In [9]:
data=pd.read_csv('Fraud  Loan Prediction.csv')

In [10]:
data=pd.DataFrame(data=data)

In [11]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
16,LP001034,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban,Y
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
19,LP001041,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban,Y
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
21,LP001046,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban,Y
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
23,LP001050,NaN,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban,N
25,LP001066,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y
26,LP001068,Male,Yes,0,Graduate,No,2799,2253.0,122.0,360.0,1.0,Semiurban,Y
27,LP001073,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,Y
28,LP001086,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban,N
29,LP001087,Female,No,2,Graduate,NaN,3750,2083.0,120.0,360.0,1.0,Semiurban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,LP002911,Male,Yes,1,Graduate,No,2787,1917.0,146.0,360.0,0.0,Rural,N
585,LP002912,Male,Yes,1,Graduate,No,4283,3000.0,172.0,84.0,1.0,Rural,N
586,LP002916,Male,Yes,0,Graduate,No,2297,1522.0,104.0,360.0,1.0,Urban,Y
587,LP002917,Female,No,0,Not Graduate,No,2165,0.0,70.0,360.0,1.0,Semiurban,Y
588,LP002925,NaN,No,0,Graduate,No,4750,0.0,94.0,360.0,1.0,Semiurban,Y
589,LP002926,Male,Yes,2,Graduate,Yes,2726,0.0,106.0,360.0,0.0,Semiurban,N
590,LP002928,Male,Yes,0,Graduate,No,3000,3416.0,56.0,180.0,1.0,Semiurban,Y
591,LP002931,Male,Yes,2,Graduate,Yes,6000,0.0,205.0,240.0,1.0,Semiurban,N
592,LP002933,NaN,No,3+,Graduate,Yes,9357,0.0,292.0,360.0,1.0,Semiurban,Y
593,LP002936,Male,Yes,0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural,Y
594,LP002938,Male,Yes,0,Graduate,Yes,16120,0.0,260.0,360.0,1.0,Urban,Y
595,LP002940,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural,Y
596,LP002941,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural,N
597,LP002943,Male,No,NaN,Graduate,No,2987,0.0,88.0,360.0,0.0,Semiurban,N
598,LP002945,Male,Yes,0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural,Y
599,LP002948,Male,Yes,2,Graduate,No,5780,0.0,192.0,360.0,1.0,Urban,Y
600,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
601,LP002950,Male,Yes,0,Not Graduate,NaN,2894,2792.0,155.0,360.0,1.0,Rural,Y
602,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y
603,LP002958,Male,No,0,Graduate,No,3676,4301.0,172.0,360.0,1.0,Rural,Y
604,LP002959,Female,Yes,1,Graduate,No,12000,0.0,496.0,360.0,1.0,Semiurban,Y
605,LP002960,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
606,LP002961,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,Y
607,LP002964,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,Y
608,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [14]:
names = ['Loan_ID','Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area','Loan_Status']

In [15]:
print(data.head(20))

     Loan_ID  Gender Married Dependents     Education Self_Employed  \
0   LP001002    Male      No          0      Graduate            No
1   LP001003    Male     Yes          1      Graduate            No
2   LP001005    Male     Yes          0      Graduate           Yes
3   LP001006    Male     Yes          0  Not Graduate            No
4   LP001008    Male      No          0      Graduate            No
5   LP001011    Male     Yes          2      Graduate           Yes
6   LP001013    Male     Yes          0  Not Graduate            No
7   LP001014    Male     Yes         3+      Graduate            No
8   LP001018    Male     Yes          2      Graduate            No
9   LP001020    Male     Yes          1      Graduate            No
10  LP001024    Male     Yes          2      Graduate            No
11  LP001027    Male     Yes          2      Graduate           NaN
12  LP001028    Male     Yes          2      Graduate            No
13  LP001029    Male      No          0      Graduate            No
14  LP001030    Male     Yes          2      Graduate            No
15  LP001032    Male      No          0      Graduate            No
16  LP001034    Male      No          1  Not Graduate            No
17  LP001036  Female      No          0      Graduate            No
18  LP001038    Male     Yes          0  Not Graduate            No
19  LP001041    Male     Yes          0      Graduate           NaN

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              5849                0.0         NaN             360.0
1              4583             1508.0       128.0             360.0
2              3000                0.0        66.0             360.0
3              2583             2358.0       120.0             360.0
4              6000                0.0       141.0             360.0
5              5417             4196.0       267.0             360.0
6              2333             1516.0        95.0             360.0
7              3036             2504.0       158.0             360.0
8              4006             1526.0       168.0             360.0
9             12841            10968.0       349.0             360.0
10             3200              700.0        70.0             360.0
11             2500             1840.0       109.0             360.0
12             3073             8106.0       200.0             360.0
13             1853             2840.0       114.0             360.0
14             1299             1086.0        17.0             120.0
15             4950                0.0       125.0             360.0
16             3596                0.0       100.0             240.0
17             3510                0.0        76.0             360.0
18             4887                0.0       133.0             360.0
19             2600             3500.0       115.0               NaN

    Credit_History Property_Area Loan_Status
0              1.0         Urban           Y
1              1.0         Rural           N
2              1.0         Urban           Y
3              1.0         Urban           Y
4              1.0         Urban           Y
5              1.0         Urban           Y
6              1.0         Urban           Y
7              0.0     Semiurban           N
8              1.0         Urban           Y
9              1.0     Semiurban           N
10             1.0         Urban           Y
11             1.0         Urban           Y
12             1.0         Urban           Y
13             1.0         Rural           N
14             1.0         Urban           Y
15             1.0         Urban           Y
16             NaN         Urban           Y
17             0.0         Urban           N
18             1.0         Rural           N
19             1.0         Urban           Y

In [22]:
data.keys()

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [23]:
data.shape

(614, 13)

In [24]:
data.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [25]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [29]:
#imputer will work for numerical data such as Dependents,Self_Employed,LoanAmount,Loan_Amount_Term,Credit_History
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN',strategy='mean')
data['Dependents']=imp.fit_transform(data['Dependents'].values.reshape(-1,1))
data['Self_Employed']=imp.fit_transform(data['Self_Employed'].values.reshape(-1,1))
data['LoanAmount']=imp.fit_transform(data['LoanAmount'].values.reshape(-1,1))
data['Loan_Amount_Term']=imp.fit_transform(data['Loan_Amount_Term'].values.reshape(-1,1))
data['Credit_History']=imp.fit_transform(data['Credit_History'].values.reshape(-1,1))

ValueError: could not convert string to float: '3+'

In [8]:
x=df1.iloc[:,0:-1]
x

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban
5,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban
6,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban
7,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban
8,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban
9,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban
10,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban
11,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban
12,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban
13,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural
14,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban
15,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban
16,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban
17,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban
18,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural
19,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban
20,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban
21,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban
22,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban
23,NaN,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural
24,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban
25,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban
26,Male,Yes,0,Graduate,No,2799,2253.0,122.0,360.0,1.0,Semiurban
27,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban
28,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban
29,Female,No,2,Graduate,NaN,3750,2083.0,120.0,360.0,1.0,Semiurban
...,...,...,...,...,...,...,...,...,...,...,...
584,Male,Yes,1,Graduate,No,2787,1917.0,146.0,360.0,0.0,Rural
585,Male,Yes,1,Graduate,No,4283,3000.0,172.0,84.0,1.0,Rural
586,Male,Yes,0,Graduate,No,2297,1522.0,104.0,360.0,1.0,Urban
587,Female,No,0,Not Graduate,No,2165,0.0,70.0,360.0,1.0,Semiurban
588,NaN,No,0,Graduate,No,4750,0.0,94.0,360.0,1.0,Semiurban
589,Male,Yes,2,Graduate,Yes,2726,0.0,106.0,360.0,0.0,Semiurban
590,Male,Yes,0,Graduate,No,3000,3416.0,56.0,180.0,1.0,Semiurban
591,Male,Yes,2,Graduate,Yes,6000,0.0,205.0,240.0,1.0,Semiurban
592,NaN,No,3+,Graduate,Yes,9357,0.0,292.0,360.0,1.0,Semiurban
593,Male,Yes,0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural
594,Male,Yes,0,Graduate,Yes,16120,0.0,260.0,360.0,1.0,Urban
595,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural
596,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural
597,Male,No,NaN,Graduate,No,2987,0.0,88.0,360.0,0.0,Semiurban
598,Male,Yes,0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural
599,Male,Yes,2,Graduate,No,5780,0.0,192.0,360.0,1.0,Urban
600,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban
601,Male,Yes,0,Not Graduate,NaN,2894,2792.0,155.0,360.0,1.0,Rural
602,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban
603,Male,No,0,Graduate,No,3676,4301.0,172.0,360.0,1.0,Rural
604,Female,Yes,1,Graduate,No,12000,0.0,496.0,360.0,1.0,Semiurban
605,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban
606,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban
607,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural
608,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban

In [1]:
df.keys()

NameError: name 'df' is not defined

In [21]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Gender','Married','Dependents','Education','Self_Employed','Property_Area','Loan_Status']
le = LabelEncoder()
for i in var_mod:
    data[i] = le.fit_transform(data[i])

TypeError: '<' not supported between instances of 'str' and 'float'

In [23]:
from sklearn.model_selection import train_test_split
array = data.values
X = array[:,6:11]
Y = array[:,12]
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=7)

NameError: name 'model_selection' is not defined

In [24]:
model = LogisticRegression()
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions))

NameError: name 'x_train' is not defined

In [25]:
model = DecisionTreeClassifier()
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions)

SyntaxError: unexpected EOF while parsing (<ipython-input-25-b3136ab1db7f>, line 4)

In [42]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
x=scale.fit_transform(x)

ValueError: could not convert string to float: 'Male'

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=43)

In [15]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
predlr=lr.predict(x_test)
print(accuracy_score,(y_test,predlr))
print(confusion_matrix,(y_test,predlr))
print(classification_report,(y_test,predlr))

ValueError: could not convert string to float: 'Semiurban'

In [26]:
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions))

NameError: name 'x_train' is not defined

In [27]:
svc=SVC(kernel='rbf')
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score,(y_test,predsvc))
print(confusion_matrix,(y_test,predsvc))
print(classification_report,(y_test,predsvc))

NameError: name 'x_train' is not defined

In [18]:
dtc=KNeighborsClassifier()
dtc.fit(x_train,y_train)
dtc.score(x_train,y_train)
preddtc=dtc.predict(x_test)
print(accuracy_score,(y_test,preddtc))
print(confusion_matrix,(y_test,preddtc))
print(classification_report,(y_test,preddtc))

ValueError: could not convert string to float: 'LP002387'

In [19]:
svc=SVC(kernel='poly')
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score,(y_test,predsvc))
print(confusion_matrix,(y_test,predsvc))
print(classification_report,(y_test,predsvc))

ValueError: could not convert string to float: 'Semiurban'

In [39]:
def svmkernel(ker):
    svc=SVC(kernel=ker)
    svc.fit(x_train,y_train)
    svc.score(x_train,y_train)
    predsvc=svc.predict(x_test)
    print(accuracy_score,(y_test,predsvc))
    print(confusion_matrix,(y_test,predsvc))
    print(classification_report,(y_test,predsvc))

In [40]:
svmkernel('rbf')

<function accuracy_score at 0x000000000BDDB620> (57     R
37     R
79     R
76     R
180    M
184    M
101    M
10     R
130    M
122    M
66     R
17     R
169    M
92     R
107    M
38     R
189    M
121    M
94     R
29     R
0      R
2      R
55     R
176    M
96     M
109    M
191    M
39     R
67     R
19     R
11     R
45     R
41     R
93     R
173    M
1      R
202    M
65     R
196    M
186    M
151    M
140    M
164    M
134    M
71     R
90     R
Name: R, dtype: object, array(['R', 'R', 'M', 'R', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'M', 'R', 'M',
       'M', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'M', 'M', 'M', 'R', 'R'], dtype=object))
<function confusion_matrix at 0x000000000BDDB6A8> (57     R
37     R
79     R
76     R
180    M
184    M
101    M
10     R
130    M
122    M
66     R
17     R
169    M
92     R
107    M
38     R
189    M
121    M
94     R
29     R
0      R
2      R
55     R
176    M
96     M
109    M
191    M
39     R
67     R
19     R
11     R
45     R
41     R
93     R
173    M
1      R
202    M
65     R
196    M
186    M
151    M
140    M
164    M
134    M
71     R
90     R
Name: R, dtype: object, array(['R', 'R', 'M', 'R', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'M', 'R', 'M',
       'M', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'M', 'M', 'M', 'R', 'R'], dtype=object))
<function classification_report at 0x000000000BDDBD08> (57     R
37     R
79     R
76     R
180    M
184    M
101    M
10     R
130    M
122    M
66     R
17     R
169    M
92     R
107    M
38     R
189    M
121    M
94     R
29     R
0      R
2      R
55     R
176    M
96     M
109    M
191    M
39     R
67     R
19     R
11     R
45     R
41     R
93     R
173    M
1      R
202    M
65     R
196    M
186    M
151    M
140    M
164    M
134    M
71     R
90     R
Name: R, dtype: object, array(['R', 'R', 'M', 'R', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'M', 'R', 'M',
       'M', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'M', 'M', 'M', 'R', 'R'], dtype=object))

In [41]:
svmkernel('poly')

<function accuracy_score at 0x000000000BDDB620> (57     R
37     R
79     R
76     R
180    M
184    M
101    M
10     R
130    M
122    M
66     R
17     R
169    M
92     R
107    M
38     R
189    M
121    M
94     R
29     R
0      R
2      R
55     R
176    M
96     M
109    M
191    M
39     R
67     R
19     R
11     R
45     R
41     R
93     R
173    M
1      R
202    M
65     R
196    M
186    M
151    M
140    M
164    M
134    M
71     R
90     R
Name: R, dtype: object, array(['R', 'R', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'R', 'M',
       'M', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'M', 'M', 'M', 'R', 'M'], dtype=object))
<function confusion_matrix at 0x000000000BDDB6A8> (57     R
37     R
79     R
76     R
180    M
184    M
101    M
10     R
130    M
122    M
66     R
17     R
169    M
92     R
107    M
38     R
189    M
121    M
94     R
29     R
0      R
2      R
55     R
176    M
96     M
109    M
191    M
39     R
67     R
19     R
11     R
45     R
41     R
93     R
173    M
1      R
202    M
65     R
196    M
186    M
151    M
140    M
164    M
134    M
71     R
90     R
Name: R, dtype: object, array(['R', 'R', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'R', 'M',
       'M', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'M', 'M', 'M', 'R', 'M'], dtype=object))
<function classification_report at 0x000000000BDDBD08> (57     R
37     R
79     R
76     R
180    M
184    M
101    M
10     R
130    M
122    M
66     R
17     R
169    M
92     R
107    M
38     R
189    M
121    M
94     R
29     R
0      R
2      R
55     R
176    M
96     M
109    M
191    M
39     R
67     R
19     R
11     R
45     R
41     R
93     R
173    M
1      R
202    M
65     R
196    M
186    M
151    M
140    M
164    M
134    M
71     R
90     R
Name: R, dtype: object, array(['R', 'R', 'M', 'M', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'R', 'M',
       'M', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'M',
       'M', 'M', 'M', 'M', 'M', 'R', 'M'], dtype=object))

In [43]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_train,y_train)
preddt=dt.predict(x_test)
print(accuracy_score,(y_test,preddt))
print(confusion_matrix,(y_test,preddt))
print(classification_report,(y_test,preddt))

<function accuracy_score at 0x000000000BDDB620> (57     R
37     R
79     R
76     R
180    M
184    M
101    M
10     R
130    M
122    M
66     R
17     R
169    M
92     R
107    M
38     R
189    M
121    M
94     R
29     R
0      R
2      R
55     R
176    M
96     M
109    M
191    M
39     R
67     R
19     R
11     R
45     R
41     R
93     R
173    M
1      R
202    M
65     R
196    M
186    M
151    M
140    M
164    M
134    M
71     R
90     R
Name: R, dtype: object, array(['R', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'R',
       'M', 'R', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'R', 'M',
       'M', 'M', 'M', 'R', 'M', 'R', 'M'], dtype=object))
<function confusion_matrix at 0x000000000BDDB6A8> (57     R
37     R
79     R
76     R
180    M
184    M
101    M
10     R
130    M
122    M
66     R
17     R
169    M
92     R
107    M
38     R
189    M
121    M
94     R
29     R
0      R
2      R
55     R
176    M
96     M
109    M
191    M
39     R
67     R
19     R
11     R
45     R
41     R
93     R
173    M
1      R
202    M
65     R
196    M
186    M
151    M
140    M
164    M
134    M
71     R
90     R
Name: R, dtype: object, array(['R', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'R',
       'M', 'R', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'R', 'M',
       'M', 'M', 'M', 'R', 'M', 'R', 'M'], dtype=object))
<function classification_report at 0x000000000BDDBD08> (57     R
37     R
79     R
76     R
180    M
184    M
101    M
10     R
130    M
122    M
66     R
17     R
169    M
92     R
107    M
38     R
189    M
121    M
94     R
29     R
0      R
2      R
55     R
176    M
96     M
109    M
191    M
39     R
67     R
19     R
11     R
45     R
41     R
93     R
173    M
1      R
202    M
65     R
196    M
186    M
151    M
140    M
164    M
134    M
71     R
90     R
Name: R, dtype: object, array(['R', 'R', 'R', 'M', 'M', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M',
       'M', 'M', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'R', 'M', 'R', 'R',
       'M', 'R', 'R', 'R', 'M', 'M', 'R', 'R', 'M', 'R', 'M', 'R', 'M',
       'M', 'M', 'M', 'R', 'M', 'R', 'M'], dtype=object))